services:
  nacos:
    image: nacos/nacos-server:v3.0.3
    container_name: spring3-nacos
    environment:
      MODE: standalone
      NACOS_AUTH_TOKEN: U3ByaW5nM0xlYXJuaW5nTmFjb3NUb2tlblNlY3JldEtleU11c3RCZUxvbmdlclRoYW4zMkNoYXJhY3RlcnM=
      NACOS_AUTH_IDENTITY_KEY: spring3
      NACOS_AUTH_IDENTITY_VALUE: spring3-local
    ports:
      - "8847:8080"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
